// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTFWgqxiVHXQdgguoDIYVwdO1GKMTwDAU',
    appId: '1:1015515769306:web:2d73de6aa3110b3fdd38e3',
    messagingSenderId: '1015515769306',
    projectId: 'lora-1-b0d0c',
    authDomain: 'lora-1-b0d0c.firebaseapp.com',
    storageBucket: 'lora-1-b0d0c.firebasestorage.app',
    measurementId: 'G-ZCBJLBZGLQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfhHv4npJh_yJ7Uc1hG58uotxOiNwrkX8',
    appId: '1:1015515769306:android:938229b02a8380fcdd38e3',
    messagingSenderId: '1015515769306',
    projectId: 'lora-1-b0d0c',
    storageBucket: 'lora-1-b0d0c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrsttPUR4DR7GM3puE8HnXzaC6qNhpmpo',
    appId: '1:1015515769306:ios:ea59006d910728c6dd38e3',
    messagingSenderId: '1015515769306',
    projectId: 'lora-1-b0d0c',
    storageBucket: 'lora-1-b0d0c.firebasestorage.app',
    iosClientId: '1015515769306-u51eslc72akma2p6o6bsnno6qsmrr596.apps.googleusercontent.com',
    iosBundleId: 'com.example.lora1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDrsttPUR4DR7GM3puE8HnXzaC6qNhpmpo',
    appId: '1:1015515769306:ios:ea59006d910728c6dd38e3',
    messagingSenderId: '1015515769306',
    projectId: 'lora-1-b0d0c',
    storageBucket: 'lora-1-b0d0c.firebasestorage.app',
    iosClientId: '1015515769306-u51eslc72akma2p6o6bsnno6qsmrr596.apps.googleusercontent.com',
    iosBundleId: 'com.example.lora1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBTFWgqxiVHXQdgguoDIYVwdO1GKMTwDAU',
    appId: '1:1015515769306:web:ad76c81b5a66753fdd38e3',
    messagingSenderId: '1015515769306',
    projectId: 'lora-1-b0d0c',
    authDomain: 'lora-1-b0d0c.firebaseapp.com',
    storageBucket: 'lora-1-b0d0c.firebasestorage.app',
    measurementId: 'G-JMC4KE1VCP',
  );

}